apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: slave
spec:
  containers:
  - name: maven
    image: maven:3.6.2-jdk-11-slim
    command:
    - cat
    tty: true
  - name: docker
    image: docker:latest
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-socket-volume
    securityContext:
      privileged: true
  volumes:
    - name: docker-socket-volume
      hostPath:
        path: /var/run/docker.sock
        type: File
  command:
  - cat
  tty: true