apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: slave
spec:
  containers:
    - command:
        - cat
      image: 'maven:3.6.2-jdk-11-slim'
      name: maven
      tty: true
    - command:
        - cat
      image: 'docker:latest'
      name: docker
      tty: true
      securityContext:
        privileged: true