apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: slave
spec:
  containers:
  - name: jnlp
    image: 'jenkinsci/jnlp-slave'
    command:
    - cat
    tty: true
  - name: maven
    image: 'maven:3.6.2-jdk-11-slim'
    command:
    - cat
    tty: true
  - name: zap
    image: 'owasp/zap2docker-stable:latest'
    command:
    - cat
    tty: true
  - name: docker
    image: 'docker:latest'
    command:
    - cat
    tty: true
    securityContext:
      privileged: true
    volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
