apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: slave
spec:
  containers:
    - command:
        - cat
      image: 'maven:3.6.2-jdk-11-slim'
      name: maven
      resources: {}
      securityContext:
      tty: true
    - command:
        - cat
      image: 'docker:latest'
      name: docker
      resources: {}
      securityContext:
        privileged: true
      tty: true
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-socket
  volumes:
    - emptyDir: {}
      name: docker-socket